services:
  backend:
    image: mubasshir090/hrms-backend:latest
    container_name: hrms_backend_prod

    ports:
      - "6543:6543"

    volumes:
      - ./uploads:/usr/src/app/uploads

    env_file:
      - ./.env

    environment:
      NODE_ENV: production
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

    restart: unless-stopped

    networks:
      - hrms-network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: hrms_redis_prod

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    restart: unless-stopped

    networks:
      - hrms-network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  hrms-network:
    driver: bridge

volumes:
  redis_data:
