export enum CandidateStatusEnum {
  APPLIED = 'APPLIED',

  SCREENING = 'SCREENING',

  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',

  INTERVIEWED = 'INTERVIEWED',

  SELECTED = 'SELECTED',

  REJECTED = 'REJECTED',

  HIRED = 'HIRED',
}
