export enum CareerMovementTypeEnum {
  PROMOTION = 'PROMOTION',
  DEMOTION = 'DEMOTION',
  TRANSFER = 'TRANSFER',
  DESIGNATION_CHANGE = 'DESIGNATION_CHANGE',
  DEPARTMENT_CHANGE = 'DEPARTMENT_CHANGE',
  TEAM_CHANGE = 'TEAM_CHANGE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  BRANCH_CHANGE = 'BRANCH_CHANGE',
  SHIFT_CHANGE = 'SHIFT_CHANGE',
  SALARY_REVISION = 'SALARY_REVISION',
  CONFIRMATION = 'CONFIRMATION',
  ACTING_ASSIGNMENT = 'ACTING_ASSIGNMENT',
}
