export enum EmploymentStatusEnum {
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  NOTICE_PERIOD = 'NOTICE_PERIOD',
  TERMINATED = 'TERMINATED',
  RESIGNED = 'RESIGNED',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}
